---
title: "List of metrics implemented in iglu"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{List of metrics implemented in iglu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(iglu)
```

|Metric Name | Corresponding function in iglu | Reference|
|------------|:------------------------------:|----------|
|Mean        | mean_glu                       |          |
|Average Daily Risk Range | adrr              |[Kovatchev et al. (2006)](https://doi.org/10.2337/dc06-1085)|
|CONGA | conga | [McDonnell et al. (2005)](https://doi.org/10.1089/dia.2005.7.253)|
|GRADE | grade | [Hill et al. (2007)](https://doi.org/10.1111/j.1464-5491.2007.02119.x)|
|GRADEeu | grade_hypo | [Hill et al. (2007)](https://doi.org/10.1111/j.1464-5491.2007.02119.x)|
|GRADEhyper | grade_hyper | [Hill et al. (2007)](https://doi.org/10.1111/j.1464-5491.2007.02119.x)|
|GRADEhypo | grade_eugly | [Hill et al. (2007)](https://doi.org/10.1111/j.1464-5491.2007.02119.x)|
|HBGI | hbgi | [Kovatchev et al. (2006)](https://doi.org/10.2337/dc06-1085)|
