data = read.csv('/share/RDirectory/iglu/Data/ExampleData1Subject.csv')

iglu::above_percent(data)
iglu::below_percent(data)
iglu::cv_glu(data)
iglu::grade(data)
iglu::grade_hyper(data)
iglu::hbgi(data)
iglu::hyper_index(data)
iglu::hypo_index(data)
iglu::igc(data)
iglu::in_range_percent(data)
iglu::iqr_glu(data)
iglu::j_index(data)
iglu::lbgi(data)
iglu::mage(data)
iglu::mean_glu(data)
iglu::quantile_glu(data)
iglu::range_glu(data)
iglu::sd_glu(data)
iglu::summary_glu(data)
s
